/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_ZiplogClientJNI */

#ifndef _Included_site_ycsb_db_ZiplogClientJNI
#define _Included_site_ycsb_db_ZiplogClientJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_ZiplogClientJNI
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_site_ycsb_db_ZiplogClientJNI_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     site_ycsb_db_ZiplogClientJNI
 * Method:    put
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_site_ycsb_db_ZiplogClientJNI_put
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
